"""initial schema

Revision ID: 0f9d27246cef
Revises: 
Create Date: 2026-09-30 03:31:07.297338

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0f9d27246cef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_installation_id')
    )
    op.create_table('ingestion_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('partition', sa.Integer(), nullable=True),
    sa.Column('offset', sa.BigInteger(), nullable=True),
    sa.Column('repository_github_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('pg_status', sa.Text(), nullable=False),
    sa.Column('index_status', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_ingestion_events_event_id')
    )
    op.create_index('ix_ingestion_events_repo_status', 'ingestion_events', ['repository_github_id', 'status'], unique=False)
    op.create_index(op.f('ix_ingestion_events_status'), 'ingestion_events', ['status'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_repository_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('default_branch', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sync_target_commit', sa.Text(), nullable=True),
    sa.Column('synced_through_commit', sa.Text(), nullable=True),
    sa.Column('backfill_published_through_commit', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sync_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repository_id')
    )
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('github_commit_sha', sa.Text(), nullable=False),
    sa.Column('parent_sha', sa.Text(), nullable=True),
    sa.Column('author_name', sa.Text(), nullable=True),
    sa.Column('author_email', sa.Text(), nullable=True),
    sa.Column('author_username', sa.Text(), nullable=True),
    sa.Column('committer_name', sa.Text(), nullable=True),
    sa.Column('committer_email', sa.Text(), nullable=True),
    sa.Column('committer_username', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_commit_sha', name='uq_commits_repo_sha')
    )
    op.create_index(op.f('ix_commits_repository_id'), 'commits', ['repository_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('current_content', sa.Text(), nullable=True),
    sa.Column('current_content_commit_sha', sa.Text(), nullable=True),
    sa.Column('current_content_commit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blob_sha', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_files_repo_path')
    )
    op.create_index(op.f('ix_files_repository_id'), 'files', ['repository_id'], unique=False)
    op.create_table('commit_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Text(), nullable=True),
    sa.Column('previous_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_id', 'file_id', name='uq_commit_files_commit_file')
    )
    op.create_index(op.f('ix_commit_files_commit_id'), 'commit_files', ['commit_id'], unique=False)
    op.create_index(op.f('ix_commit_files_file_id'), 'commit_files', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commit_files_file_id'), table_name='commit_files')
    op.drop_index(op.f('ix_commit_files_commit_id'), table_name='commit_files')
    op.drop_table('commit_files')
    op.drop_index(op.f('ix_files_repository_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_commits_repository_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_ingestion_events_status'), table_name='ingestion_events')
    op.drop_index('ix_ingestion_events_repo_status', table_name='ingestion_events')
    op.drop_table('ingestion_events')
    op.drop_table('github_installations')
    # ### end Alembic commands ###
